# Generated by Django 5.2.17 on 2026-09-14 00:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=12)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('digest', models.CharField(max_length=64, unique=True)),
                ('scopes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamcomms_service.membership')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('human', 'Human'), ('ai', 'Ai'), ('program', 'Program'), ('connector', 'Connector')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='teamcomms_service.participant')),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='participant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='teamcomms_service.participant'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('singleton', models.BooleanField(default=True, editable=False, unique=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('singleton', True)), name='tc_one_team')],
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamcomms_service.team'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['human', 'ai', 'program', 'connector'])), name='tc_participant_kind'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['admin', 'member'])), name='tc_membership_role'),
        ),
    ]
