# Generated by Django 5.2.17 on 2026-09-14 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamcomms_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostIdentityBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=120)),
                ('subject', models.CharField(max_length=255)),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='teamcomms_service.membership')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'subject'), name='tc_host_subject')],
            },
        ),
    ]
