# Generated by Django 5.2.17 on 2026-09-14 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teamcomms_comms', '0002_immutable_records'),
        ('teamcomms_entries', '0004_editplan_integrity'),
        ('teamcomms_service', '0002_host_identity_binding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='teamcomms_entries.entry')),
                ('generation', models.PositiveIntegerField(default=1)),
                ('state', models.CharField(default='planned', max_length=16)),
                ('form', models.CharField(default='work', max_length=16)),
                ('visibility', models.CharField(default='operator', max_length=16)),
                ('detail', models.JSONField(default=dict)),
                ('handoff', models.JSONField(null=True)),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executed_work', to='teamcomms_service.participant')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_work', to='teamcomms_service.participant')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='teamcomms_inflight.work')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='teamcomms_comms.session')),
            ],
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dependents', to='teamcomms_inflight.work')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dependencies', to='teamcomms_inflight.work')),
            ],
        ),
        migrations.CreateModel(
            name='WorkReceipt',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('request', models.JSONField()),
                ('result', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamcomms_service.participant')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamcomms_entries.entry')),
            ],
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['state', 'visibility'], name='tc_work_view'),
        ),
        migrations.AddConstraint(
            model_name='work',
            constraint=models.CheckConstraint(condition=models.Q(('generation__gte', 1)), name='tc_work_generation'),
        ),
        migrations.AddConstraint(
            model_name='work',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['planned', 'active', 'blocked', 'completed', 'failed', 'canceled'])), name='tc_work_state'),
        ),
        migrations.AddConstraint(
            model_name='dependency',
            constraint=models.UniqueConstraint(fields=('work', 'prerequisite'), name='tc_work_dependency'),
        ),
    ]
