# Generated by Django 5.2.17 on 2026-09-14 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamcomms_comms', '0002_immutable_records'),
        ('teamcomms_inflight', '0002_guards'),
        ('teamcomms_service', '0002_host_identity_binding'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinationReceipt',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('request', models.JSONField()),
                ('result', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamcomms_service.participant')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamcomms_service.team')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceCustody',
            fields=[
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='teamcomms_comms.resource')),
                ('generation', models.PositiveIntegerField(default=1)),
                ('protection', models.CharField(default='advisory', max_length=20)),
                ('transfer', models.JSONField(null=True)),
                ('custodian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamcomms_service.participant')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOffer',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('generation', models.PositiveIntegerField()),
                ('specification', models.JSONField()),
                ('expires_at', models.DateTimeField()),
                ('state', models.CharField(default='open', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='teamcomms_inflight.work')),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('generation', models.PositiveIntegerField()),
                ('state', models.CharField(default='active', max_length=12)),
                ('deadline', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamcomms_service.participant')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='teamcomms_comms.session')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='teamcomms_inflight.work')),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='teamcomms_inflight.workoffer')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='teamcomms_inflight.claim')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='teamcomms_inflight.resourcecustody')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('active', True)), fields=('resource',), name='tc_reservation_exclusive'), models.UniqueConstraint(fields=('claim', 'resource'), name='tc_claim_resource')],
            },
        ),
        migrations.AddConstraint(
            model_name='claim',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'active')), fields=('work',), name='tc_claim_one_active'),
        ),
    ]
