# Generated by Django 5.2.17 on 2026-09-14 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamcomms_inflight', '0003_coordinationreceipt_resourcecustody_workoffer_claim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardRun',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('resource_ids', models.JSONField()),
                ('command_sha256', models.CharField(max_length=64)),
                ('state', models.CharField(default='active', max_length=12)),
                ('outcome', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guard_runs', to='teamcomms_inflight.claim')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('state', 'active')), fields=('claim',), name='tc_guard_one_active')],
            },
        ),
    ]
