# Generated by Django 5.2.17 on 2026-09-15 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamcomms_inflight', '0005_claim_integrity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionRun',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('command_sha256', models.CharField(max_length=64)),
                ('specification', models.JSONField()),
                ('state', models.CharField(default='active', max_length=12)),
                ('result', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='execution_run', to='teamcomms_inflight.claim')),
            ],
        ),
    ]
