# Generated by Django 5.2.17 on 2026-09-14 01:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teamcomms_entries', '0002_integrity_and_search'),
        ('teamcomms_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=160)),
                ('name', models.CharField(max_length=160)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamcomms_service.team')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('envelope', models.JSONField()),
                ('author_snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamcomms_service.participant')),
                ('reply_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='teamcomms_comms.message')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamcomms_service.team')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveBigIntegerField()),
                ('state', models.CharField(default='pending', max_length=16)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('detail', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(null=True)),
                ('considered_at', models.DateTimeField(null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='teamcomms_comms.message')),
            ],
        ),
        migrations.CreateModel(
            name='MessageReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamcomms_entries.entry')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamcomms_comms.message')),
                ('revision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='teamcomms_entries.revision')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('request', models.JSONField()),
                ('result', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamcomms_service.participant')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='teamcomms_comms.delivery')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=240)),
                ('kind', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=160)),
                ('host', models.CharField(blank=True, max_length=160)),
                ('aliases', models.JSONField(default=list)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='teamcomms_comms.resource')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamcomms_service.team')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('native_id', models.CharField(max_length=160)),
                ('client', models.CharField(max_length=80)),
                ('host', models.CharField(max_length=160)),
                ('name', models.CharField(max_length=160)),
                ('workspace', models.CharField(blank=True, max_length=4096)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('effort', models.CharField(blank=True, max_length=40)),
                ('capabilities', models.JSONField(default=list)),
                ('delivery_mode', models.CharField(default='pull', max_length=40)),
                ('state', models.CharField(default='unknown', max_length=16)),
                ('last_seen', models.DateTimeField()),
                ('last_sequence', models.PositiveBigIntegerField(default=0)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamcomms_service.membership')),
                ('resources', models.ManyToManyField(to='teamcomms_comms.resource')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='sender_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='teamcomms_comms.session'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamcomms_comms.session'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=160)),
                ('active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='teamcomms_comms.group')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamcomms_comms.session')),
            ],
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('team', 'key'), name='tc_group_key'),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.UniqueConstraint(fields=('team', 'key'), name='tc_resource_key'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['host', 'last_seen'], name='tc_session_host_seen'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(fields=('membership', 'host', 'client', 'native_id'), name='tc_session_native'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['author', '-created_at'], name='tc_message_author'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.UniqueConstraint(fields=('message', 'session'), name='tc_delivery_destination'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.UniqueConstraint(fields=('session', 'sequence'), name='tc_delivery_sequence'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['pending', 'written', 'accepted', 'uncertain', 'failed'])), name='tc_delivery_state'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('session', 'group'), name='tc_subscription_group'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('group__isnull', True)), fields=('session', 'topic'), name='tc_subscription_topic'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('group__isnull', False), ('topic', '')), models.Q(('group__isnull', True), models.Q(('topic', ''), _negated=True)), _connector='OR'), name='tc_subscription_target'),
        ),
    ]
