# Generated by Django 5.2.17 on 2026-09-14 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teamcomms_comms', '0002_immutable_records'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=240)),
                ('source_sequence', models.PositiveBigIntegerField()),
                ('run_id', models.CharField(blank=True, max_length=160)),
                ('occurred_at', models.DateTimeField()),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(max_length=16)),
                ('phase', models.CharField(max_length=16)),
                ('content', models.TextField()),
                ('topic', models.CharField(blank=True, max_length=160)),
                ('attribution', models.JSONField()),
                ('request', models.JSONField()),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='teamcomms_comms.message')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamcomms_comms.session')),
            ],
            options={
                'indexes': [models.Index(fields=['session', '-id'], name='tc_dialog_session'), models.Index(fields=['topic', 'occurred_at'], name='tc_dialog_topic_time')],
                'constraints': [models.UniqueConstraint(fields=('session', 'source_id'), name='tc_dialog_source')],
            },
        ),
    ]
