# Generated by Django 5.2.17 on 2026-09-14 00:39

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teamcomms_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(blank=True, max_length=120, null=True)),
                ('kind', models.CharField(max_length=32)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('state', models.JSONField()),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamcomms_service.participant')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamcomms_service.team')),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('base_revision', models.PositiveIntegerField()),
                ('state', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamcomms_service.participant')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='teamcomms_entries.entry')),
                ('restored_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='teamcomms_entries.revision')),
            ],
        ),
        migrations.CreateModel(
            name='RevisionReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(max_length=60)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='references', to='teamcomms_entries.revision')),
                ('target_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamcomms_entries.entry')),
                ('target_revision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='teamcomms_entries.revision')),
            ],
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['team', '-modified_at', 'id'], name='tc_entry_modified'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['team', 'kind'], name='tc_entry_kind'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=django.contrib.postgres.indexes.GinIndex(fields=['state'], name='tc_entry_state'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='tc_entry_search'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.UniqueConstraint(fields=('team', 'slug'), name='tc_entry_slug'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='tc_entry_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='revision',
            constraint=models.UniqueConstraint(fields=('entry', 'number'), name='tc_revision_number'),
        ),
        migrations.AddConstraint(
            model_name='revision',
            constraint=models.UniqueConstraint(fields=('entry', 'id'), name='tc_revision_entry_id'),
        ),
        migrations.AddConstraint(
            model_name='revision',
            constraint=models.CheckConstraint(condition=models.Q(('number__gte', 1)), name='tc_revision_positive'),
        ),
    ]
