# Generated by Django 5.2.17 on 2026-09-14 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamcomms_entries', '0002_integrity_and_search'),
        ('teamcomms_service', '0002_host_identity_binding'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditPlan',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('request', models.JSONField()),
                ('prepared', models.JSONField()),
                ('result', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamcomms_service.participant')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamcomms_service.team')),
            ],
        ),
    ]
