# Generated by Django 5.2.17 on 2026-09-14 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teamcomms_entries', '0003_editplan'),
        ('teamcomms_service', '0002_host_identity_binding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pouch',
            fields=[
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='teamcomms_service.team')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='teamcomms_entries.entry')),
            ],
        ),
    ]
