# Generated by Django 5.2.17 on 2026-09-14 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teamcomms_inflight', '0005_claim_integrity'),
        ('teamcomms_comms', '0002_immutable_records'),
        ('teamcomms_entries', '0004_editplan_integrity'),
        ('teamcomms_service', '0002_host_identity_binding'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttentionPolicy',
            fields=[
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='teamcomms_comms.session')),
                ('revision', models.PositiveIntegerField(default=1)),
                ('routine_mode', models.CharField(default='immediate', max_length=16)),
                ('batch_seconds', models.PositiveIntegerField(default=30)),
                ('quiet_until', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MutationReceipt',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('request', models.JSONField()),
                ('result', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamcomms_service.participant')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamcomms_service.team')),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='teamcomms_comms.delivery')),
                ('disposition', models.CharField(max_length=16)),
                ('due_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coalesced_into', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='teamcomms_comms.delivery')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=160)),
                ('title', models.CharField(max_length=240)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('links', models.JSONField(default=dict)),
                ('last_sequence', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamcomms_service.participant')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamcomms_service.team')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveBigIntegerField()),
                ('kind', models.CharField(max_length=20)),
                ('urgency', models.CharField(max_length=16)),
                ('content', models.TextField()),
                ('source', models.CharField(blank=True, max_length=240)),
                ('observed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamcomms_service.participant')),
                ('published_message', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capcom_notice', to='teamcomms_comms.message')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamcomms_capcom.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following', models.BooleanField(default=False)),
                ('read_sequence', models.PositiveBigIntegerField(default=0)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamcomms_service.participant')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamcomms_capcom.topic')),
            ],
        ),
        migrations.CreateModel(
            name='TopicRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('state', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamcomms_service.participant')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamcomms_capcom.topic')),
            ],
        ),
        migrations.CreateModel(
            name='TopicReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamcomms_entries.entry')),
                ('revision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='teamcomms_entries.revision')),
                ('topic_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamcomms_capcom.topicrevision')),
            ],
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('notice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='teamcomms_capcom.notice')),
                ('revision', models.PositiveIntegerField(default=1)),
                ('resolution', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(null=True)),
                ('resolved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='teamcomms_service.participant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('team', 'key'), name='tc_topic_key'),
        ),
        migrations.AddConstraint(
            model_name='notice',
            constraint=models.UniqueConstraint(fields=('topic', 'sequence'), name='tc_notice_sequence'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('topic', 'participant'), name='tc_topic_follow'),
        ),
        migrations.AddConstraint(
            model_name='topicrevision',
            constraint=models.UniqueConstraint(fields=('topic', 'number'), name='tc_topic_revision'),
        ),
    ]
