# Generated by Django 5.2.17 on 2026-09-14 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamcomms_capcom', '0002_integrity'),
        ('teamcomms_comms', '0002_immutable_records'),
        ('teamcomms_service', '0002_host_identity_binding'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamcomms_comms.message')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamcomms_service.participant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('participant', 'message'), name='tc_capcom_conversation_read')],
            },
        ),
    ]
